# perintah tertinggi
sudo: required

# pilih OS trusty
dist: trusty

#bahasa yg digunakan
language: php

#versi bahasa 
php:
    - 7.1

#branch
branches:
    only:
        - master
        - develop
#before install
before_install:
    - wget https://phar.phpunit.de/phpunit-6.5.phar
    - chmod +x phpunit-6.5.phar
    - sudo mv phpunit-6.5.phar /usr/local/bin/phpunit
    - phpunit --version

#install
install:


#before script
before_script:


#script
script: